--liquibase formatted sql

--changeset jenol:003-1a dbms:oracle

-- BIBLIOTEKA.USERS-1 definition

CREATE TABLE "BIBLIOTEKA"."USERS" (
	"USERNAME" NVARCHAR2(128),
	"PASSWORD" NVARCHAR2(128) NOT NULL ENABLE,
	"ENABLED" CHAR(1) NOT NULL ENABLE,
	 CHECK (ENABLED IN ('Y','N') ) DISABLE,
	 PRIMARY KEY ("USERNAME")
)
TABLESPACE "USERS";


-- BIBLIOTEKA.AUTHORITIES definition

CREATE TABLE "BIBLIOTEKA"."AUTHORITIES" (
	"USERNAME" NVARCHAR2(128) NOT NULL ENABLE,
	"AUTHORITY" NVARCHAR2(128) NOT NULL ENABLE,
	 CONSTRAINT "AUTHORITIES_UNIQUE" UNIQUE ("USERNAME", "AUTHORITY"),
	 CONSTRAINT "AUTHORITIES_FK1" FOREIGN KEY ("USERNAME")
	 REFERENCES "BIBLIOTEKA"."USERS" ("USERNAME") ENABLE
)
TABLESPACE "USERS";

--changeset jenol:003-1b dbms:h2

-- BIBLIOTEKA.USERS-1 definition

CREATE TABLE USERS (
    USERNAME NVARCHAR2(128) PRIMARY KEY,
	PASSWORD NVARCHAR2(128) NOT NULL,
	ENABLED CHAR(1) NOT NULL
);


-- BIBLIOTEKA.AUTHORITIES definition

CREATE TABLE AUTHORITIES (
	USERNAME NVARCHAR2(128) NOT NULL,
	AUTHORITY NVARCHAR2(128) NOT NULL,
	PRIMARY KEY (USERNAME, AUTHORITY),
	FOREIGN KEY (USERNAME) REFERENCES USERS(USERNAME)
);

--changeset jenol:003-2

INSERT INTO USERS (USERNAME, PASSWORD, ENABLED) VALUES('user', '$2a$10$SJliLkhfuTofYZUh5P/MSuC4EmgKQT4XTI5km.iLV6ZIP7cBDZmcW', '1');
INSERT INTO USERS (USERNAME, PASSWORD, ENABLED) VALUES('admin', '$2a$10$TYNTUvyoDBvgSc/JzK2sHetSLs2gDXzc5Q1gwvIRif7jp7ns9.1se', '1');

INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES('admin', 'ROLE_ADMIN');
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES('admin', 'ROLE_USER');
INSERT INTO AUTHORITIES (USERNAME, AUTHORITY) VALUES('user', 'ROLE_USER');